apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: <PLURAL>.bifrost.mastercard.com
spec:
  group: bifrost.mastercard.com
  names:
    kind: <KIND>
    plural: <PLURAL>
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: phase
          jsonPath: .status.phase
          name: phase
          type: string
        - description: status
          jsonPath: .status.status
          name: status
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                status:
                  type: string
                message:
                  type: string
                reason:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    additionalProperties:
                      x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}